name: build

on:
  push:
env:
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
      - run: |
          asdf plugin add nodejs
          asdf install nodejs
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: npm ci
      - run: npm test --if-present
      - run: npm run build:vercel -- --prod --token=${{ secrets.VERCEL_TOKEN }}
  migrate:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    if: ${{ github.ref_name  }} == 'main'
    steps:
      - uses: actions/checkout@v4
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
      - run: |
          asdf plugin add nodejs
          asdf install nodejs
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm ci
      - run: prisma migrate deploy
  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: migrate
    if: ${{ github.ref_name  }} == 'main'
    steps:
      - uses: actions/checkout@v4
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
      - run: |
          asdf plugin add nodejs
          asdf install nodejs
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm ci
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy
